
// async.h
// + Request numbers
// + Sub-request numbers.
// Created by Fred Nora.

#ifndef __ASYNC_H
#define __ASYNC_H    1

// Shutdown the server.
#define ASYNC_REQUEST_EXIT  1
#define ASYNC_REQUEST_HELLO2  2
#define ASYNC_REQUEST_HELLO3  3
#define ASYNC_REQUEST_START_ANIMATION  4  
#define ASYNC_REQUEST_FPS_FLAG  6  
#define ASYNC_REQUEST_SET_FOCUS_BY_WID  9
#define ASYNC_REQUEST_SWITCH_ACTIVE_WINDOW  12 
#define ASYNC_REQUEST_INVALIDATE_WINDOW_BY_WID  13
#define ASYNC_REQUEST_CLEAR_WINDOW_BY_WID  14
#define ASYNC_REQUEST_SET_ACTIVE_WINDOW_BY_WID  15
#define ASYNC_REQUEST_LAUNCH_SHUTDOWN  22
#define ASYNC_REQUEST_ENABLE_PS2_MOUSE  44
#define ASYNC_REQUEST_QUIT  88
#define ASYNC_REQUEST_REBOOT  89
#define ASYNC_REQUEST_DESTROY_WINDOW  90
#define ASYNC_REQUEST_PUT_PIXEL  1000

#endif   

