
all:

# We do not compile the libs here anymore
# It is compiled in the root folder of the project.
#	make -C libs/

	make -C demo01/
#...

clean:
	-rm -f *.o 
clean-all:
	-rm -f *.o 
#	-rm -f bin/*.BIN
