// honey.h
// Color theme for the color scheme.
// Created by Fred Nora.

#ifndef __HONEY_H
#define __HONEY_H    1

/*
#define HONEY_COLOR_BACKGROUND                 0x00909497 //0x00008080 
#define HONEY_COLOR_WINDOW                     0x00FFFFFF 
#define HONEY_COLOR_WINDOW_BACKGROUND          COLOR_GRAY  //0x00202020 
#define HONEY_COLOR_ACTIVE_WINDOW_BORDER       0x00404040 
#define HONEY_COLOR_INACTIVE_WINDOW_BORDER     0x00606060
// Titlebar for active window.
// Light blue (Um pouco fosco) 
#define HONEY_COLOR_ACTIVE_WINDOW_TITLEBAR  0x00A9CCE3  //COLOR_BLUE1
#define HONEY_COLOR_INACTIVE_WINDOW_TITLEBAR   0x00606060 
#define HONEY_COLOR_MENUBAR                    0x00808080 
#define HONEY_COLOR_SCROLLBAR                  0x00FFF5EE 
#define HONEY_COLOR_STATUSBAR                  0x0083FCFF
// Taskbar for the window manager.
#define HONEY_COLOR_TASKBAR  0x00C3C3C3 
#define HONEY_COLOR_MESSAGEBOX      0x00404040 
#define HONEY_COLOR_SYSTEMFONT      0x00000000 
#define HONEY_COLOR_TERMINALFONT    0x00FFFFFF 
#define HONEY_COLOR_BUTTON  0x00C3C3C3 
// Window border
#define HONEY_COLOR_WINDOW_BORDER  COLOR_INACTIVEBORDER
// Window with focus border
#define HONEY_COLOR_WWF_BORDER  COLOR_BLUE
#define HONEY_COLOR_TITLEBAR_TEXT  COLOR_WHITE
// When mouse hover.
#define HONEY_COLOR_BG_ONMOUSEHOVER  xCOLOR_GRAY3
#define HONEY_COLOR_BG_ONMOUSEHOVER_MIN_CONTROL  COLOR_BLUE
#define HONEY_COLOR_BG_ONMOUSEHOVER_MAX_CONTROL  COLOR_BLUE
#define HONEY_COLOR_BG_ONMOUSEHOVER_CLO_CONTROL  COLOR_RED
//...
// --------------------
*/

#define HONEY_COLOR_BACKGROUND                 0x00505050 
#define HONEY_COLOR_WINDOW                     0x00d4d0c8
#define HONEY_COLOR_WINDOW_BACKGROUND          COLOR_GRAY  //0x00202020 
#define HONEY_COLOR_ACTIVE_WINDOW_BORDER       0x006e2209
#define HONEY_COLOR_INACTIVE_WINDOW_BORDER     0x00808080
// Titlebar for active window.
// Light blue (Um pouco fosco) 
#define HONEY_COLOR_ACTIVE_WINDOW_TITLEBAR  0x00A9CCE3  //COLOR_BLUE1
#define HONEY_COLOR_INACTIVE_WINDOW_TITLEBAR   0x00606060 
#define HONEY_COLOR_MENUBAR                    0x00808080 
#define HONEY_COLOR_SCROLLBAR                  0x00FFF5EE 
#define HONEY_COLOR_STATUSBAR                  0x0083FCFF
// Taskbar for the window manager.
#define HONEY_COLOR_TASKBAR  0x00C3C3C3 
#define HONEY_COLOR_MESSAGEBOX      0x00404040 
#define HONEY_COLOR_SYSTEMFONT      0x00000000 
#define HONEY_COLOR_TERMINALFONT    0x00FFFFFF 
#define HONEY_COLOR_BUTTON  0x00d4d0c8 
// Window border
#define HONEY_COLOR_WINDOW_BORDER  COLOR_INACTIVEBORDER
// Window with focus border
#define HONEY_COLOR_WWF_BORDER  COLOR_BLUE
//#define HONEY_COLOR_TITLEBAR_TEXT  COLOR_WHITE
#define HONEY_COLOR_TITLEBAR_TEXT  COLOR_BLACK
// When mouse hover.
#define HONEY_COLOR_BG_ONMOUSEHOVER  xCOLOR_GRAY3
#define HONEY_COLOR_BG_ONMOUSEHOVER_MIN_CONTROL  COLOR_BLUE
#define HONEY_COLOR_BG_ONMOUSEHOVER_MAX_CONTROL  COLOR_BLUE
#define HONEY_COLOR_BG_ONMOUSEHOVER_CLO_CONTROL  COLOR_RED
//...
// --------------------


#endif   


