
# Compile commands/

all:

# Libraries
	make -C alpha/

# Commands
	make -C c4/
	make -C cat/
	make -C cmp/
	make -C false/
	make -C gramc4/
	make -C gramcnf/
	make -C miniyacc/
	make -C n9/
	make -C n10/
	make -C n11/
	make -C pubsh/
	make -C reboot/
	#make -C rect/
	#make -C replace/
	make -C sh7/
	make -C shell/
	#make -C shell2/
	make -C showfun/
	make -C shutdown/
	#make -C socket1/
	make -C sum/
	make -C tascii/
	make -C tprintf/
	make -C true/
	#make -C tty/
	make -C uname/
	#make -C unknown/
	
clean:
	-rm bin/*.BIN
clean-all:
	-rm -f alpha/libs/libio01/obj/*.o
	-rm -f alpha/libs/rtl/obj/*.o
	-rm bin/*.BIN
	
	

