
all:
	make -C libs/

clean:
	#-rm -f libs/libcpp/obj/*.o
	-rm -f libs/libdisp/obj/*.o
	-rm -f libs/libgr/obj/*.o
	-rm -f libs/libgr3d/obj/*.o
	-rm -f libs/libgws/obj/*.o
	-rm -f libs/libio01/obj/*.o
	-rm -f libs/rtl/obj/*.o

